DragonFlyAdmin/DragonFlyAdmin/Models/Location.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace DragonFlyAdmin.Models
{
    public partial class Location
    {
        public Location()
        {
            ResourceLocations = new HashSet<ResourceLocation>();
        }

        public int Id { get; set; }
        public string Location1 { get; set; }
        public string ZipCode { get; set; }
        public string EntryUser { get; set; }
        public DateTime EntryDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDt { get; set; }

        public virtual ICollection<ResourceLocation> ResourceLocations { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Locations/LocationView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace DragonFlyAdmin.ViewModels.Locations
{
    public partial class LocationView
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Location is Required")]
        [MaxLength(250)]
        public string Location { get; set; }
        [Required(ErrorMessage = "Zip Code is Required")]
        [MaxLength(100)]
        public string ZipCode { get; set; }
        [DisplayName("Entry User")]
        [MaxLength(100)]
        public string EntryUser { get; set; }
        [DisplayName("Entry Date")]
        [DataType(DataType.DateTime)]
        public DateTime EntryDate { get; set; }
        [DisplayName("Update User")]
        [MaxLength(100)]
        public string UpdateUser { get; set; }
        [DisplayName("Update Date")]
        [DataType(DataType.DateTime)]
        public DateTime? UpdateDt { get; set; }
        public bool IsAdmin { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Locations/LocationsEditModel.cs
using DragonFlyAdmin.Models;

namespace DragonFlyAdmin.ViewModels.Locations
{
    public class LocationEditModel : LocationView
    {
        public bool IsAdmin { get; set; }
        public bool IsMember { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Locations/LocationsIndexModel.cs
using System.Collections.Generic;
using DragonFlyAdmin.Models;

namespace DragonFlyAdmin.ViewModels.Locations
{
    public class LocationsIndexModel : LocationView
    {
        public List<LocationView> LocationList { get; set; }
        public bool IsAdmin { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/Controllers/LocationsController.cs
using DragonFlyAdmin.Interfaces;
using DragonFlyAdmin.Models;
using DragonFlyAdmin.Services;
using DragonFlyAdmin.ViewModels.Locations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DragonFlyAdmin.Controllers
{
    /// <summary>
    /// This controller handles all add/remove/edit for locations
    /// </summary>
    public class LocationsController : Controller, ILoggerInterface
    {
        private readonly DragonflyContext _context;
        private readonly LoggerService _logger;
        private readonly string _userId;
        private readonly AdService _adService;
        /// <summary>
        /// Default constructor for creating all instances of services
        /// </summary>
        /// <param name="context">dbContext</param>
        /// <param name="accessor">logged in user</param>
        public LocationsController(DragonflyContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _logger = CreateLogger();
            _adService = new AdService(accessor);
            _userId = _adService.CleanUsername(_adService.GetUserName());
        }
        /// <summary>
        /// Main index page for Locations
        /// </summary>
        /// <returns>Index view with list of locations</returns>
        public async Task<IActionResult> Index()
        {
            try
            {
                var locations = await _context.Locations.OrderBy(x => x.Location1).ToListAsync();
                var locationList = locations.Select(location => new Location()
                {
                    Id = location.Id,
                    Location1 = location.Location1,
                    ZipCode = location.ZipCode,
                    EntryUser = location.EntryUser,
                    EntryDate = location.EntryDate,
                    UpdateUser = location.UpdateUser,
                    UpdateDt = location.UpdateDt
                })
                    .ToList();
                var model = new LocationsIndexModel()
                {
                    LocationList = BuildLocationViews(locationList),
                    IsAdmin = _adService.IsAdmin()
                };
                return View(model);
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Locations::Index :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }
        /// <summary>
        /// Builds a list of ViewModel Locations from DB Model Locations
        /// </summary>
        /// <param name="locationList">db locations</param>
        /// <returns>view model locations</returns>
        private List<LocationView> BuildLocationViews(IEnumerable<Location> locationList)
        {
            return locationList.Select(location => new LocationView
            {
                Id = location.Id,
                Location = location.Location1,
                ZipCode = location.ZipCode,
                EntryDate = location.EntryDate,
                EntryUser = location.EntryUser,
                UpdateDt = location.UpdateDt,
                UpdateUser = location.UpdateUser
            })
                .ToList();
        }
        /// <summary>
        /// Builds a ViewModel Location out of a DB Model Location
        /// </summary>
        /// <param name="location">db location</param>
        /// <returns>view model location</returns>
        private LocationView BuildLocationView(Location location)
        {
            return new LocationView
            {
                Id = location.Id,
                Location = location.Location1,
                ZipCode = location.ZipCode,
                EntryDate = location.EntryDate,
                EntryUser = location.EntryUser,
                UpdateDt = location.UpdateDt,
                UpdateUser = location.UpdateUser,
                IsAdmin = _adService.IsAdmin()
            };
        }
        /// <summary>
        /// Displays the details of a location
        /// </summary>
        /// <param name="id">location id</param>
        /// <returns>Detail View</returns>
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var location = await _context.Locations
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (location == null)
                {
                    return NotFound();
                }

                return View(BuildLocationView(location));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Locations::Details({id}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }

        }
        /// <summary>
        /// Displays the Create screen for adding new location
        /// </summary>
        /// <returns>Create View</returns>
        public IActionResult Create()
        {
            var location = new Location()
            {
                EntryDate = DateTime.Now,
                EntryUser = _userId
            };
            return View(BuildLocationView(location));
        }
        /// <summary>
        /// Saves a new Location to the database
        /// </summary>
        /// <param name="locationView">form</param>
        /// <returns>Index for Locations</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Location,ZipCode,EntryUser")] LocationView locationView)
        {
            try
            {
                var location = new Location
                {
                    Location1 = locationView.Location,
                    ZipCode = locationView.ZipCode,
                    EntryUser = _userId,
                    EntryDate = DateTime.Now
                };

                if (!ModelState.IsValid) return View(BuildLocationView(location));
                if (_context.Locations.Any(x => x.Location1 == locationView.Location && x.ZipCode == locationView.ZipCode))
                //if (_context.Locations.Any(x => x.Location1 == locationView.Location))
                {
                    ViewData["Unique"] = $"Location '{locationView.Location}' already exists.";
                    return View(BuildLocationView(location));
                }

                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Locations::Create({JsonConvert.SerializeObject(locationView)}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }

        }
        /// <summary>
        /// Displays the Edit screen for a location
        /// </summary>
        /// <param name="id">location id</param>
        /// <returns>Edit Location View</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var location = await _context.Locations.FindAsync(id);
                if (location == null) return NotFound();
                location.UpdateDt = DateTime.Now;
                location.UpdateUser = _userId;
                return View(BuildLocationEditModel(location));

            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Locations::Edit({id}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }

        }
        /// <summary>
        /// Saves the edited location to the databse
        /// </summary>
        /// <param name="id">location id</param>
        /// <param name="locationModel">form</param>
        /// <returns>Index of Locations</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Location,ZipCode,EntryUser,EntryDate,UpdateUser,UpdateDt")] LocationEditModel locationModel)
        {
            try
            {
                if (id != locationModel.Id)
                {
                    return NotFound();
                }
                var location = await _context.Locations.Where(x => x.Id == id).FirstAsync();
                location.Location1 = locationModel.Location;
                location.ZipCode = locationModel.ZipCode;
                location.UpdateDt = DateTime.Now;
                location.UpdateUser = _userId;
                if (!ModelState.IsValid) return View(BuildLocationEditModel(location));
                // if name changed and exists already
                if (location.Location1 != locationModel.Location && _context.Locations.Any(x => x.Location1 == locationModel.Location))
                {
                    ViewData["Unique"] = $"Location '{locationModel.Location}' already exists.";
                    return View(BuildLocationEditModel(location));
                }

                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                    ViewData["Success"] = $"{locationModel.Location} Successfully Updated!";
                }
                catch (DbUpdateConcurrencyException eu)
                {
                    if (!LocationExists(locationModel.Id))
                    {
                        _logger.WriteError(
                            $"DBException :: Not Found :: Locations::Edit({id}:{JsonConvert.SerializeObject(locationModel)}) :: {eu.Message}");
                        return NotFound();

DragonFlyAdmin/DragonFlyAdmin/Views/Locations/Create.cshtml
@model DragonFlyAdmin.ViewModels.Locations.LocationView

@{
    ViewData["Title"] = "Create";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h1>Create Location</h1>
    <h2 class="redfont">@ViewData["Unique"]</h2>
    <h2 class="greenfont">@ViewData["Success"]</h2>
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (@Html.BeginForm("Index", "Locations", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>
<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="EntryDate"/>
                <input type="hidden" asp-for="EntryUser"/>
                <div class="form-group">
                    <label asp-for="Location" class="col-form-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ZipCode" class="col-form-label"></label>
                    <input asp-for="ZipCode" class="form-control" />
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryUser" class="col-form-label"></label>
                    <input asp-for="EntryUser" class="form-control" disabled/>
                    <span asp-validation-for="EntryUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryDate" class="col-form-label"></label>
                    <input asp-for="EntryDate" class="form-control" disabled/>
                    <span asp-validation-for="EntryDate" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-4 col-md-4 col-lg-4 float-left">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DragonFlyAdmin/DragonFlyAdmin/Views/Locations/Delete.cshtml
@model DragonFlyAdmin.ViewModels.Locations.LocationView

@{
    ViewData["Title"] = "Delete";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h1>Delete Location</h1>
    <h1>Are you sure you want to delete this?</h1>
    <h2 class="redfont">All deleted records will be logged!</h2>
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (@Html.BeginForm("Index", "Locations", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.Location): </span>
            <span>@Html.DisplayFor(model => model.Location)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.ZipCode): </span>
            <span>@Html.DisplayFor(model => model.ZipCode)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryUser): </span>
            <span>@Html.DisplayFor(model => model.EntryUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryDate): </span>
            <span>@Html.DisplayFor(model => model.EntryDate)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateUser): </span>
            <span>@Html.DisplayFor(model => model.UpdateUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateDt): </span>
            <span>@Html.DisplayFor(model => model.UpdateDt)</span>
        </div>
    </div>
    <div class="row float-right">
        @if (Model.IsAdmin)
        {
            @using (@Html.BeginForm("Delete", "Locations", new { id = @Model.Id }, FormMethod.Post))
            {
                <button class="btn btn-danger">Delete</button>
            }
        }
    </div>
</div>

DragonFlyAdmin/DragonFlyAdmin/Views/Locations/Details.cshtml
@model DragonFlyAdmin.ViewModels.Locations.LocationView

@{
    ViewData["Title"] = "Details";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar form-inline">
    <h1>Insurance Details</h1>
    @using (@Html.BeginForm("Index", "Locations", FormMethod.Get))
    {
        <button class="btn btn-info">Back to List</button>
    }
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.Location): </span>
            <span>@Html.DisplayFor(model => model.Location)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.ZipCode): </span>
            <span>@Html.DisplayFor(model => model.ZipCode)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryUser): </span>
            <span>@Html.DisplayFor(model => model.EntryUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryDate): </span>
            <span>@Html.DisplayFor(model => model.EntryDate)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateUser): </span>
            <span>@Html.DisplayFor(model => model.UpdateUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateDt): </span>
            <span>@Html.DisplayFor(model => model.UpdateDt)</span>
        </div>
    </div>
    <div class="row float-right">
        @using (@Html.BeginForm("Edit", "Locations", new { id = @Model.Id }, FormMethod.Get))
        {
            <button class="btn btn-primary">Edit</button>
        }
    </div>
</div>

DragonFlyAdmin/DragonFlyAdmin/Views/Locations/Edit.cshtml
@model DragonFlyAdmin.ViewModels.Locations.LocationEditModel

@{
    ViewData["Title"] = "Edit";
}

<div class="col-sm-12 col-md-12 col-lg-12 topbar form-inline">
    <h1>Edit Location</h1>
    <h2 class="redfont">@ViewData["Unique"]</h2>
    <h2 class="greenfont">@ViewData["Success"]</h2>
    <div class="form-group col-sm-6 col-md-6 col-lg-6">
        @using (@Html.BeginForm("Index", "Locations", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id"/>
                <input type="hidden" asp-for="UpdateUser"/>
                <input type="hidden" asp-for="EntryUser"/>
                <div class="form-group">
                    <label asp-for="Location" class="col-form-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ZipCode" class="col-form-label"></label>
                    <input asp-for="ZipCode" class="form-control"/>
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryUser" class="col-form-label"></label>
                    <input asp-for="EntryUser" class="form-control" disabled/>
                    <span asp-validation-for="EntryUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryDate" class="col-form-label"></label>
                    <input asp-for="EntryDate" class="form-control" disabled/>
                    <span asp-validation-for="EntryDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpdateUser" class="col-form-label"></label>
                    <input asp-for="UpdateUser" class="form-control" disabled/>
                    <span asp-validation-for="UpdateUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpdateDt" class="col-form-label"></label>
                    <input asp-for="UpdateDt" class="form-control" disabled/>
                    <span asp-validation-for="UpdateDt" class="text-danger"></span>
                </div>
                @if (@Model.IsAdmin || @Model.IsMember)
                {
                    <div class="form-group col-sm-6 col-md-6 col-lg-6 float-left">
                        <input type="submit" value="Save" class="btn btn-primary"/>
                    </div>
                }
                else
                {
                    <p>You are not authorized to make changes</p>
                }
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DragonFlyAdmin/DragonFlyAdmin/Views/Locations/Index.cshtml
@model DragonFlyAdmin.ViewModels.Locations.LocationsIndexModel

@{
    ViewData["Title"] = "Index";
}

<div class="col-sm-12 col-md-12 col-lg-12">
    <h1>Locations</h1>
    @using (@Html.BeginForm("Create", "Locations", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-primary">Create New</button></span>
    }
    @using (@Html.BeginForm("Index", "Admin", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-info">Back to List</button></span>
    }
</div>
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Location)</th>
                <th>@Html.DisplayNameFor(model => model.ZipCode)</th>
                <th>@Html.DisplayNameFor(model => model.EntryUser)</th>
                <th>@Html.DisplayNameFor(model => model.EntryDate)</th>
                <th>@Html.DisplayNameFor(model => model.UpdateUser)</th>
                <th>@Html.DisplayNameFor(model => model.UpdateDt)</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.LocationList) {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Location)</td>
                <td>@Html.DisplayFor(modelItem => item.ZipCode)</td>
                <td>@Html.DisplayFor(modelItem => item.EntryUser)</td>
                <td>@Html.DisplayFor(modelItem => item.EntryDate)</td>
                <td>@Html.DisplayFor(modelItem => item.UpdateUser)</td>
                <td>@Html.DisplayFor(modelItem => item.UpdateDt)</td>
                <td>
                    @using (@Html.BeginForm("Edit", "Locations", new {id=@item.Id}, FormMethod.Get))
                    {
                        <button class="btn btn-info">Edit</button>
                    }
                </td>
                <td>
                    @using (@Html.BeginForm("Details", "Locations", new {id=@item.Id}, FormMethod.Get))
                    {
                        <button class="btn btn-primary">Details</button>
                    }
                </td>    
                @if (Model.IsAdmin)
                {
                    <td>
                        @using (@Html.BeginForm("Delete", "Locations", new { id = @item.Id }, FormMethod.Get))
                        {
                            <button class="btn btn-danger">Delete</button>
                        }
                    </td>
                }
            </tr>
    }
        </tbody>
    </table>