DragonFlyAdmin/DragonFlyAdmin/Models/Service.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace DragonFlyAdmin.Models
{
    public partial class Service
    {
        public Service()
        {
            ResourceServices = new HashSet<ResourceService>();
        }

        public int Id { get; set; }
        public string Service1 { get; set; }
        public string EntryUser { get; set; }
        public DateTime EntryDt { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDt { get; set; }

        public virtual ICollection<ResourceService> ResourceServices { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Services/ServiceView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace DragonFlyAdmin.ViewModels.Services
{
    public partial class ServiceView
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Service Name is required")]
        [DisplayName("Service Name")]
        public string Service { get; set; }
        [DisplayName("Entry User")]
        [MaxLength(100)]
        public string EntryUser { get; set; }
        [DisplayName("Entry Date")]
        [DataType(DataType.DateTime)]
        public DateTime EntryDt { get; set; }
        [DisplayName("Update User")]
        [MaxLength(100)]
        public string UpdateUser { get; set; }
        [DisplayName("Update Date")]
        [DataType(DataType.DateTime)]
        public DateTime? UpdateDt { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Services/ServicesEditModel.cs
using DragonFlyAdmin.Models;

namespace DragonFlyAdmin.ViewModels.Services
{
    public class ServicesEditModel : ServiceView
    {
        public bool IsAdmin { get; set; }
        public bool IsMember { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Services/ServicesIndexModel.cs
using System.Collections.Generic;
using DragonFlyAdmin.Models;

namespace DragonFlyAdmin.ViewModels.Services
{
    public class ServicesIndexModel : ServiceView
    {
        public List<ServiceView> ServiceList { get; set; }
        public bool IsAdmin { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DragonFlyAdmin.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DragonFlyAdmin.Models;
using DragonFlyAdmin.Services;
using DragonFlyAdmin.ViewModels.Services;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace DragonFlyAdmin.Controllers
{
    /// <summary>
    /// This controller handles all add/remove/edit for Services
    /// </summary>
    public class ServicesController : Controller, ILoggerInterface
    {
        private readonly DragonflyContext _context;
        private readonly LoggerService _logger;
        private readonly string _userId;
        private readonly AdService _adService;
        /// <summary>
        /// Default Constructor that creates instances of all services needed
        /// </summary>
        /// <param name="context">dbContext</param>
        /// <param name="accessor">logged in user</param>
        public ServicesController(DragonflyContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _logger = CreateLogger();
            _adService = new AdService(accessor);
            _userId = _adService.CleanUsername(_adService.GetUserName());
        }
        /// <summary>
        /// Builds a vm model list for Services from a db model list
        /// </summary>
        /// <param name="serviceList">list of services from db</param>
        /// <returns>vm list of services</returns>
        private List<ServiceView> BuildServiceViews(IEnumerable<Service> serviceList)
        {
            return serviceList.Select(service => new ServiceView
                {
                    Id = service.Id,
                    Service = service.Service1,
                    EntryDt = service.EntryDt,
                    EntryUser = service.EntryUser,
                    UpdateDt = service.UpdateDt,
                    UpdateUser = service.UpdateUser
                })
                .ToList();
        }
        /// <summary>
        /// Builds a vm model from a db model of Services
        /// </summary>
        /// <param name="service">db service</param>
        /// <returns>vm service</returns>
        private ServiceView BuildServiceView(Service service)
        {
            return new ServiceView
            {
                Id = service.Id,
                Service = service.Service1,
                EntryDt = service.EntryDt,
                EntryUser = service.EntryUser,
                UpdateDt = service.UpdateDt,
                UpdateUser = service.UpdateUser
            };
        }
        /// <summary>
        /// Main Index View
        /// </summary>
        /// <returns>list of Services</returns>
        public async Task<IActionResult> Index()
        {
            try
            {
                var services = await _context.Services.OrderBy(x => x.Service1).ToListAsync();
                var servicesList = services.Select(service => new Service()
                    {
                        Id = service.Id,
                        Service1 = service.Service1,
                        EntryUser = service.EntryUser,
                        EntryDt = service.EntryDt,
                        UpdateUser = service.UpdateUser,
                        UpdateDt = service.UpdateDt
                    })
                    .ToList();
                var model = new ServicesIndexModel()
                {
                    ServiceList = BuildServiceViews(servicesList),
                    IsAdmin = _adService.IsAdmin()
                };
                return View(model);
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Services::Index() :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }
        /// <summary>
        /// Displays the Service Detail Page
        /// </summary>
        /// <param name="id">service id</param>
        /// <returns>Detail View</returns>
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var service = await _context.Services
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (service == null)
                {
                    return NotFound();
                }

                return View(BuildServiceView(service));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Services::Details({id}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
            
        }
        /// <summary>
        /// Displays the Create view
        /// </summary>
        /// <returns>Create View</returns>
        public IActionResult Create()
        {
            var service = new Service()
            {
                EntryDt = DateTime.Now,
                EntryUser = _userId
            };
            return View(BuildServiceView(service));
        }
        /// <summary>
        /// Creates a new Service in the DB
        /// </summary>
        /// <param name="serviceView">form</param>
        /// <returns>Services index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Service,EntryUser,EntryDt")] ServiceView serviceView)
        {
            try
            {
                var service = new Service()
                {
                    Service1 = serviceView.Service,
                    EntryDt = DateTime.Now,
                    EntryUser = _userId
                };
                if (!ModelState.IsValid) return View(BuildServiceView(service));

                if (_context.Services.Any(x => x.Service1 == serviceView.Service))
                {
                    ViewData["Unique"] = $"Service '{serviceView.Service}' already exists.";
                    return View(BuildServiceView(service));
                }

                _context.Add(service);
                await _context.SaveChangesAsync();
                ViewData["Success"] = $"{serviceView.Service} Successfully Created!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Services::Create({JsonConvert.SerializeObject(serviceView)}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
            
        }
        /// <summary>
        /// Displays the edit page for a Service
        /// </summary>
        /// <param name="id">service id</param>
        /// <returns>Edit View</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var service = await _context.Services.FindAsync(id);
                if (service == null) return NotFound();
                service.UpdateDt = DateTime.Now;
                service.UpdateUser = _userId;

                return View(BuildServiceEditModel(service));

            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Services::Edit({id}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
            
        }
        /// <summary>
        /// Saves changes to Service in db
        /// </summary>
        /// <param name="id">service id</param>
        /// <param name="serviceModel">form</param>
        /// <returns>Services Index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Service,EntryUser,EntryDt,UpdateUser,UpdateDt")] ServicesEditModel serviceModel)
        {
            try
            {
                if (id != serviceModel.Id)
                {
                    return NotFound();
                }
                var service = await _context.Services.Where(x => x.Id == id).FirstAsync();
                service.Service1 = serviceModel.Service;
                service.UpdateDt = DateTime.Now;
                service.UpdateUser = _userId;
                if (!ModelState.IsValid)
                {
                    return View(BuildServiceEditModel(service));
                }
                // if name changed and exists already
                if (service.Service1 == serviceModel.Service && _context.Services.Any(x => x.Service1 == serviceModel.Service))
                {
                    ViewData["Unique"] = $"Service '{serviceModel.Service}' already exists.";
                    return View(BuildServiceEditModel(service));
                }
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                    ViewData["Success"] = $"{serviceModel.Service} Successfully Updated!";
                }
                catch (DbUpdateConcurrencyException eu)
                {
                    if (!ServiceExists(serviceModel.Id))
                    {
                        _logger.WriteError($"DBException :: Not Found :: Services::Edit({id}:{JsonConvert.SerializeObject(serviceModel)}) :: {eu.Message}");
                        return NotFound();
                    }
                    _logger.WriteError($"DBException :: Services::Edit({id}:{JsonConvert.SerializeObject(serviceModel)}) :: {eu.Message}");
                    return RedirectToAction("Error", "Home");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

DragonFlyAdmin/DragonFlyAdmin/Views/Services/Create.cshtml
@model DragonFlyAdmin.ViewModels.Services.ServiceView

@{
    ViewData["Title"] = "Create";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h1>Create Service</h1>
    <h2 class="redfont">@ViewData["Unique"]</h2>
    <h2 class="greenfont">@ViewData["Success"]</h2>
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (@Html.BeginForm("Index", "Services", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>
<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="EntryDt"/>
                <input type="hidden" asp-for="EntryUser"/>
                <div class="form-group">
                    <label asp-for="Service" class="col-form-label"></label>
                    <input asp-for="Service" class="form-control" />
                    <span asp-validation-for="Service" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryUser" class="col-form-label"></label>
                    <input asp-for="EntryUser" class="form-control" disabled=""/>
                    <span asp-validation-for="EntryUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryDt" class="col-form-label"></label>
                    <input asp-for="EntryDt" class="form-control" disabled/>
                    <span asp-validation-for="EntryDt" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-4 col-md-4 col-lg-4 float-left">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DragonFlyAdmin/DragonFlyAdmin/Views/Services/Delete.cshtml
@model DragonFlyAdmin.ViewModels.Services.ServicesEditModel

@{
    ViewData["Title"] = "Delete";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h1>Delete Service</h1>
    <h1>Are you sure you want to delete this?</h1>
    <h2 class="redfont">All deleted records will be logged!</h2>
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (@Html.BeginForm("Index", "Services", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.Service): </span>
            <span>@Html.DisplayFor(model => model.Service)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryUser): </span>
            <span>@Html.DisplayFor(model => model.EntryUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryDt): </span>
            <span>@Html.DisplayFor(model => model.EntryDt)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateUser): </span>
            <span>@Html.DisplayFor(model => model.UpdateUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateDt): </span>
            <span>@Html.DisplayFor(model => model.UpdateDt)</span>
        </div>
    </div>
    <div class="row float-right">
        @if (Model.IsAdmin)
        {
            @using (@Html.BeginForm("Delete", "Services", new { id = @Model.Id }, FormMethod.Post))
            {
                <button class="btn btn-danger">Delete</button>
            }
        }
    </div>
</div>

DragonFlyAdmin/DragonFlyAdmin/Views/Services/Details.cshtml
@model DragonFlyAdmin.ViewModels.Services.ServiceView

@{
    ViewData["Title"] = "Details";
}
<div class="col-sm-12 col-md-12 col-lg-12">
    <h1>Service Details</h1>
    @using (@Html.BeginForm("Index", "Services", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-info">Back to List</button></span>
    }
    @using (@Html.BeginForm("Edit", "Services", new { id = @Model.Id }, FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-primary">Edit</button></span>
    }
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.Service): </span>
            <span>@Html.DisplayFor(model => model.Service)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryUser): </span>
            <span>@Html.DisplayFor(model => model.EntryUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryDt): </span>
            <span>@Html.DisplayFor(model => model.EntryDt)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateUser): </span>
            <span>@Html.DisplayFor(model => model.UpdateUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateDt): </span>
            <span>@Html.DisplayFor(model => model.UpdateDt)</span>
        </div>
    </div>
</div>

DragonFlyAdmin/DragonFlyAdmin/Views/Services/Edit.cshtml
@model DragonFlyAdmin.ViewModels.Services.ServicesEditModel

@{
    ViewData["Title"] = "Edit";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar form-inline">
    <h1>Edit Service</h1>
    <h2 class="redfont">@ViewData["Unique"]</h2>
    <h2 class="greenfont">@ViewData["Success"]</h2>
    <div class="form-group col-sm-6 col-md-6 col-lg-6">
        @using (@Html.BeginForm("Index", "Services", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id"/>
                <input type="hidden" asp-for="UpdateUser"/>
                <input type="hidden" asp-for="EntryUser"/>
                <div class="form-group">
                    <label asp-for="Service" class="col-form-label"></label>
                    <input asp-for="Service" class="form-control" />
                    <span asp-validation-for="Service" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryUser" class="col-form-label"></label>
                    <input asp-for="EntryUser" class="form-control" disabled/>
                    <span asp-validation-for="EntryUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryDt" class="col-form-label"></label>
                    <input asp-for="EntryDt" class="form-control" disabled/>
                    <span asp-validation-for="EntryDt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpdateUser" class="col-form-label"></label>
                    <input asp-for="UpdateUser" class="form-control" disabled/>
                    <span asp-validation-for="UpdateUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpdateDt" class="col-form-label"></label>
                    <input asp-for="UpdateDt" class="form-control" disabled/>
                    <span asp-validation-for="UpdateDt" class="text-danger"></span>
                </div>
                @if (@Model.IsAdmin || @Model.IsMember)
                {
                    <div class="form-group col-sm-6 col-md-6 col-lg-6 float-left">
                        <input type="submit" value="Save" class="btn btn-primary"/>
                    </div>
                }
                else
                {
                    <p>You are not authorized to make changes</p>
                }
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DragonFlyAdmin/DragonFlyAdmin/Views/Services/Index.cshtml
@model DragonFlyAdmin.ViewModels.Services.ServicesIndexModel

@{
    ViewData["Title"] = "Index";
}
<div class="col-sm-12 col-md-12 col-lg-12 form-inline topbar">
    <h1>Services</h1>
    @using (@Html.BeginForm("Create", "Services", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-primary">Create</button></span>
    }
    @using (@Html.BeginForm("Index", "Admin", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-info">Back to List</button></span>
    }
</div>
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Service)</th>
                <th>@Html.DisplayNameFor(model => model.EntryUser)</th>
                <th>@Html.DisplayNameFor(model => model.EntryDt)</th>
                <th>@Html.DisplayNameFor(model => model.UpdateUser)</th>
                <th>@Html.DisplayNameFor(model => model.UpdateDt)</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.ServiceList) {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Service)</td>
                <td>@Html.DisplayFor(modelItem => item.EntryUser)</td>
                <td>@Html.DisplayFor(modelItem => item.EntryDt)</td>
                <td>@Html.DisplayFor(modelItem => item.UpdateUser)</td>
                <td>@Html.DisplayFor(modelItem => item.UpdateDt)</td>
                <td>
                    @using (@Html.BeginForm("Edit", "Services", new {id=@item.Id}, FormMethod.Get))
                    {
                        <button class="btn btn-primary">Edit</button>
                    }
                </td>
                <td>
                    @using (@Html.BeginForm("Details", "Services", new {id=@item.Id}, FormMethod.Get))
                    {
                        <button class="btn btn-primary">Details</button>
                    }
                </td>    
                @if (Model.IsAdmin)
                {
                    <td>
                        @using (@Html.BeginForm("Delete", "Services", new { id = @item.Id }, FormMethod.Get))
                        {
                            <button class="btn btn-danger">Delete</button>
                        }
                    </td>
                }
            </tr>
    }
        </tbody>
    </table>