DragonFlyAdmin/DragonFlyAdmin/Models/Age.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace DragonFlyAdmin.Models
{
    public partial class Age
    {
        public Age()
        {
            ResourceAges = new HashSet<ResourceAge>();
        }

        public int Id { get; set; }
        public string Age1 { get; set; }
        public string EntryUser { get; set; }
        public DateTime EntryDt { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDt { get; set; }

        public virtual ICollection<ResourceAge> ResourceAges { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Ages/AgeEditModel.cs
using DragonFlyAdmin.Models;

namespace DragonFlyAdmin.ViewModels.Ages
{
    public class AgeEditModel : AgeView
    {
        public bool IsAdmin { get; set; }
        public bool IsMember { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Ages/AgeIndexModel.cs
using System.Collections.Generic;
using DragonFlyAdmin.Models;

namespace DragonFlyAdmin.ViewModels.Ages
{
    public class AgeIndexModel
    {
        public List<AgeView> AgeRangeList { get; set; }
        public bool IsAdmin { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/ViewModels/Ages/AgeView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace DragonFlyAdmin.ViewModels.Ages
{
    public partial class AgeView
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Age is Required")]
        [MaxLength(50)]
        public string Age { get; set; }
        [DisplayName("Entry User")]
        [MaxLength(100)]
        public string EntryUser { get; set; }
        [DisplayName("Entry Date")]
        [DataType(DataType.DateTime)]
        public DateTime EntryDt { get; set; }
        [DisplayName("Update User")]
        [MaxLength(100)]
        public string UpdateUser { get; set; }
        [DisplayName("Update Date")]
        [DataType(DataType.DateTime)]
        public DateTime? UpdateDt { get; set; }
    }
}

DragonFlyAdmin/DragonFlyAdmin/Controllers/AgesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DragonFlyAdmin.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DragonFlyAdmin.Models;
using DragonFlyAdmin.Services;
using DragonFlyAdmin.ViewModels.Ages;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace DragonFlyAdmin.Controllers
{
    /// <summary>
    /// This controller handles all add/remove/edit functions for Ages
    /// </summary>
    public class AgesController : Controller, ILoggerInterface
    {
        private readonly DragonflyContext _context;
        private readonly LoggerService _logger;
        private readonly string _userId;
        private readonly AdService _adService;
        public AgesController(DragonflyContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _logger = CreateLogger();
            _adService = new AdService(accessor);
            _userId = _adService.CleanUsername(_adService.GetUserName());
        }
        /// <summary>
        /// Displays the initial Index page for Ages
        /// </summary>
        /// <returns>Index view with list of Ages</returns>
        public async Task<IActionResult> Index()
        {
            try
            {
                var model = new AgeIndexModel();

                var ages = await _context.Ages.ToListAsync();
                var ageList = ages.Select(age => new AgeView
                    {
                        Id = age.Id,
                        Age = age.Age1,
                        EntryDt = age.EntryDt,
                        EntryUser = age.EntryUser,
                        UpdateDt = age.UpdateDt,
                        UpdateUser = age.UpdateUser
                    })
                    .ToList();
                model.AgeRangeList = ageList;
                model.IsAdmin = _adService.IsAdmin();
                return View(model);
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception Ages::Index() :: {e.Message} ");
                return RedirectToAction("Error", "Home");
            }
        }

        /// <summary>
        /// Gets the Details of the Age
        /// </summary>
        /// <param name="id">selected age</param>
        /// <returns>Age View</returns>
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var age = await _context.Ages
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (age == null)
                {
                    return NotFound();
                }

                return View(BuildAgeView(age));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Ages::Details({id}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
            
        }
        /// <summary>
        /// Builds the Model for the Ages View
        /// </summary>
        /// <param name="age">Age to View</param>
        /// <returns>AgeView Model</returns>
        private AgeView BuildAgeView(Age age)
        {
           return new AgeView()
            {
                Id = age.Id,
                Age = age.Age1,
                EntryDt = age.EntryDt,
                EntryUser = age.EntryUser,
                UpdateDt = age.UpdateDt,
                UpdateUser = age.UpdateUser
            };

        }
        /// <summary>
        /// Loads the Create Page with Model
        /// </summary>
        /// <returns>Model to the Create new Age Screen</returns>
        public IActionResult Create()
        {

            var age = new AgeView()
            {
                EntryDt = DateTime.Now,
                EntryUser = _userId
            };
            return View(age);
        }
        /// <summary>
        /// Creates a new Age
        /// </summary>
        /// <param name="ageView">Age from Form</param>
        /// <returns>Ages Index Page</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Age,EntryUser,EntryDt")] AgeView ageView)
        {
            try
            {
                var age = new Age
                {
                    Age1 = ageView.Age,
                    EntryUser = _userId,
                    EntryDt = DateTime.Now
                };
                if (!ModelState.IsValid) return View(BuildAgeView(age));

                if (_context.Ages.Any(x => x.Age1 == ageView.Age))
                {
                    ViewData["Unique"] = $"AgeRange '{ageView.Age}' already exists.";
                    return View(BuildAgeView(age));
                }
                
                _context.Add(age);
                await _context.SaveChangesAsync();
                ViewData["Success"] = $"{ageView.Age} Successfully Created!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Ages::Create({JsonConvert.SerializeObject(ageView)}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
            
        }
        /// <summary>
        /// Loads the Edit Page for selected Age
        /// </summary>
        /// <param name="id">Age id</param>
        /// <returns>Edit Screen for selected Age</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var age = await _context.Ages.FindAsync(id);
                if (age == null) return NotFound();
                age.UpdateDt = DateTime.Now;
                age.UpdateUser = _userId;
                return View(BuildAgeEditModel(age));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Ages::Edit ({id}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
           
        }
        /// <summary>
        /// This builds the Age View model from the db Age
        /// </summary>
        /// <param name="age">db age</param>
        /// <returns>view model age</returns>
        private AgeEditModel BuildAgeEditModel(Age age)
        {
            var isMember = _adService.IsMember();
            var isAdmin = _adService.IsAdmin();
            var model = new AgeEditModel
            {
                Id = age.Id,
                Age = age.Age1,
                EntryDt = age.EntryDt,
                EntryUser = age.EntryUser,
                UpdateDt = age.UpdateDt,
                UpdateUser = age.UpdateUser,
                IsAdmin = isAdmin,
                IsMember = isMember
            };
            return model;
        }
        /// <summary>
        /// Post Edited Age to the database
        /// </summary>
        /// <param name="id">age id</param>
        /// <param name="ageEditModel">Updated Model from the form on the edit screen</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Age,EntryUser,EntryDt,UpdateUser,UpdateDt")] AgeEditModel ageEditModel)
        {
            try
            {
                if (id != ageEditModel.Id)
                {
                    return NotFound();
                }

                var model = await _context.Ages.Where(x => x.Id == id).FirstAsync();
                model.Age1 = ageEditModel.Age;
                model.UpdateDt = DateTime.Now;
                model.UpdateUser = _userId;
                if (!ModelState.IsValid) return View(BuildAgeEditModel(model));
                // if name changed and exists already
                if (model.Age1 == ageEditModel.Age && _context.Ages.Any(x => x.Age1 == ageEditModel.Age))
                {
                    ViewData["Unique"] = $"AgeRange '{ageEditModel.Age}' already exists.";
                    return View(BuildAgeEditModel(model));
                }
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    ViewData["Success"] = $"{ageEditModel.Age} Successfully Updated!";
                }
                catch (DbUpdateConcurrencyException eu)
                {
                    if (!AgeExists(ageEditModel.Id))
                    {
                        _logger.WriteError($"Exception :: Not Found :: Ages::Edit({id}:{JsonConvert.SerializeObject(ageEditModel)}) :: {eu.Message}");
                        return NotFound();
                    }
                    _logger.WriteError($"Exception :: DbUpdateConcurrencyException :: Ages::Edit({id}::{JsonConvert.SerializeObject(ageEditModel)}) :: {eu.Message}");
                    return RedirectToAction("Error", "Home");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.WriteError($"Exception :: Ages::Edit({id}:{JsonConvert.SerializeObject(ageEditModel)}) :: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
            
        }
       /// <summary>
       /// Displays the delete screen for selected age
       /// </summary>
       /// <param name="id">Age id</param>
       /// <returns>Delete View</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var age = await _context.Ages
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (age == null)

DragonFlyAdmin/DragonFlyAdmin/Views/Ages/Create.cshtml
@model DragonFlyAdmin.ViewModels.Ages.AgeView

@{
    ViewData["Title"] = "Create";
}

<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h2 class="redfont">@ViewData["Unique"]</h2>
    <h2 class="greenfont">@ViewData["Success"]</h2>
    <h1>Create Age Range</h1>
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (@Html.BeginForm("Index", "Ages", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>

<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <form asp-action="Create">
                <input type="hidden" asp-for="EntryDt"/>
                <input type="hidden" asp-for="EntryUser"/>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12">
                    <label asp-for="Age" class="col-form-label"></label>
                    <input asp-for="Age" class="form-control"/>
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryUser" class="col-form-label"></label>
                    <input asp-for="EntryUser" class="form-control" disabled/>
                    <span asp-validation-for="EntryUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryDt" class="col-form-label"></label>
                    <input asp-for="EntryDt" class="form-control" disabled/>
                    <span asp-validation-for="EntryDt" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-4 col-md-4 col-lg-4 float-right">
                    <input type="submit" value="Create" class="btn btn-primary"/>
                </div>
            </form>
           
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DragonFlyAdmin/DragonFlyAdmin/Views/Ages/Delete.cshtml
@model DragonFlyAdmin.ViewModels.Ages.AgeEditModel

@{
    ViewData["Title"] = "Delete";
}

<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h1>Delete Age</h1>
    <h1>Are you sure you want to delete this?</h1>
    <h2 class="redfont">All deleted records will be logged!</h2>
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (@Html.BeginForm("Index", "Ages", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.Age): </span>
            <span>@Html.DisplayFor(model => model.Age)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryUser): </span>
            <span>@Html.DisplayFor(model => model.EntryUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryDt): </span>
            <span>@Html.DisplayFor(model => model.EntryDt)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateUser): </span>
            <span>@Html.DisplayFor(model => model.UpdateUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateDt): </span>
            <span>@Html.DisplayFor(model => model.UpdateDt)</span>
        </div>
    </div>
    <div class="row float-right">
        @if (Model.IsAdmin)
        {
            @using (@Html.BeginForm("Delete", "Ages", new { id = @Model.Id }, FormMethod.Post))
            {
                <button class="btn btn-danger">Delete</button>
            }
        }
    </div>
</div>

DragonFlyAdmin/DragonFlyAdmin/Views/Ages/Details.cshtml
@model DragonFlyAdmin.ViewModels.Ages.AgeView

@{
    ViewData["Title"] = "Details";
}

<div class="col-sm-12 col-md-12 col-lg-12 topbar">
    <h1>Age Range Details</h1>
    @using (@Html.BeginForm("Index", "Ages", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-info">Back to List</button></span>
    }
    @using (@Html.BeginForm("Edit", "Ages", new { id = @Model.Id }, FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-primary">Edit</button></span>
    }
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.Age): </span>
            <span>@Html.DisplayFor(model => model.Age)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryUser): </span>
            <span>@Html.DisplayFor(model => model.EntryUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.EntryDt): </span>
            <span>@Html.DisplayFor(model => model.EntryDt)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateUser): </span>
            <span>@Html.DisplayFor(model => model.UpdateUser)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <span class="col-form-label-lg font-weight-bold">@Html.DisplayNameFor(model => model.UpdateDt): </span>
            <span>@Html.DisplayFor(model => model.UpdateDt)</span>
        </div>
    </div>
</div>

DragonFlyAdmin/DragonFlyAdmin/Views/Ages/Edit.cshtml
@model DragonFlyAdmin.ViewModels.Ages.AgeEditModel

@{
    ViewData["Title"] = "Edit";
}
<div class="col-sm-12 col-md-12 col-lg-12 topbar form-inline">
    <h1>Edit Age</h1>
    <h2 class="redfont">@ViewData["Unique"]</h2>
    <h2 class="greenfont">@ViewData["Success"]</h2>
    <div class="form-group col-sm-6 col-md-6 col-lg-6">
        @using (@Html.BeginForm("Index", "Ages", FormMethod.Get))
        {
            <button class="btn btn-info">Back to List</button>
        }
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="UpdateUser"/>
                <input type="hidden" asp-for="EntryUser"/>
                <div class="form-group">
                    <label asp-for="Age" class="col-form-label"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryUser" class="col-form-label"></label>
                    <input asp-for="EntryUser" class="form-control" disabled/>
                    <span asp-validation-for="EntryUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryDt" class="col-form-label"></label>
                    <input asp-for="EntryDt" class="form-control" disabled/>
                    <span asp-validation-for="EntryDt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpdateUser" class="col-form-label"></label>
                    <input asp-for="UpdateUser" class="form-control" disabled/>
                    <span asp-validation-for="UpdateUser" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UpdateDt" class="col-form-label"></label>
                    <input asp-for="UpdateDt" class="form-control" disabled/>
                    <span asp-validation-for="UpdateDt" class="text-danger"></span>
                </div>
                @if (@Model.IsAdmin||@Model.IsMember)
                {
                    <div class="form-group col-sm-6 col-md-6 col-lg-6 float-right">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                }
                else
                {
                    <p>You are not authorized to make changes</p>
                }
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DragonFlyAdmin/DragonFlyAdmin/Views/Ages/Index.cshtml
@using System.Linq
@model DragonFlyAdmin.ViewModels.Ages.AgeIndexModel

@{
    ViewData["Title"] = "Index";
}
<div class="col-sm-12 col-md-12 col-lg-12 form-inline topbar">
    <h1>Ages</h1>
    @using (@Html.BeginForm("Create", "Ages", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-primary">Create</button></span>
    }
    @using (@Html.BeginForm("Index", "Admin", FormMethod.Get))
    {
        <span class="col-sm-6 col-md-6 col-lg-6"><button class="btn btn-info">Back to List</button></span>
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.AgeRangeList.First().Age)</th>
            <th>@Html.DisplayNameFor(model => model.AgeRangeList.First().EntryUser)</th>
            <th>@Html.DisplayNameFor(model => model.AgeRangeList.First().EntryDt)</th>
            <th>@Html.DisplayNameFor(model => model.AgeRangeList.First().UpdateUser)</th>
            <th>@Html.DisplayNameFor(model => model.AgeRangeList.First().UpdateDt)</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.AgeRangeList) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Age)</td>
            <td>@Html.DisplayFor(modelItem => item.EntryUser)</td>
            <td>@Html.DisplayFor(modelItem => item.EntryDt)</td>
            <td>@Html.DisplayFor(modelItem => item.UpdateUser)</td>
            <td>@Html.DisplayFor(modelItem => item.UpdateDt)</td>
            <td>
                @using (@Html.BeginForm("Edit", "Ages", new {id=@item.Id}, FormMethod.Get))
                {
                    <button class="btn btn-info">Edit</button>
                }
            </td>
            <td>
                @using (@Html.BeginForm("Details", "Ages", new {id=@item.Id}, FormMethod.Get))
                {
                    <button class="btn btn-primary">Details</button>
                }
            </td>    
            @if (Model.IsAdmin)
            {
                <td>
                    @using (@Html.BeginForm("Delete", "Ages", new {id=@item.Id}, FormMethod.Get))
                    {
                        <button class="btn btn-danger">Delete</button>
                    }
                </td>
            }
        </tr>
}
    </tbody>
</table>